### ISSUE TITLE
add existing wham code

### ISSUE THREAD

**Issue by ppxasjsm** [markovmodel/pyfeat#3]
incorporate wham estimator in new force and reader framework.

**Comment by ppxasjsm** [comment]
Does it make sense to have a p_K_i for wham, or any umbrella sampling simulation?

**Comment by cwehmeyer** [comment]
Do you mean pi_K_i?
That would make sense. You can compute these values easily.

**Comment by ppxasjsm** [comment]
its not about easy compuation, its about why do I want to know what my probability at bias K would be to be in markov state i

**Comment by ppxasjsm** [comment]
it would be this right:
`self._pi_K_i = self.f_K[:,np.newaxis] * self.pi_i[np.newaxis,:] * self.gamma_K_i`

**Comment by cwehmeyer** [comment]
Yes, but why self._pi_K_i?

**Comment by ppxasjsm** [comment]
as a getter, to be constistent with dTRAM

**Comment by cwehmeyer** [comment]
OK, I agree!
But we have to make sure that the getter recalculates pi_K_i after f_K and/or pi_i changes.

**Comment by ppxasjsm** [comment]
Maybe always recalculate when called?

**Comment by cwehmeyer** [comment]
That's not necessary. dTRAM should handle that by means of a recalculate flag that's set to True in the sc_iteration method.
But since it is a very cheap operation, we could just always recalculate...

**Comment by ppxasjsm** [comment]
done
